Repository SSUMC-7th/Spring_Boot_C, pull requests merged in 2024-11, with the labels that each got.

#21 [Maro] Chapter 6. JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/QFoodCategory.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QTerms.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QMemberAgree.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/generated/umc/spring/domain/mapping/QMemberPrefer.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/domain/mapping/MemberPrefer.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#19 [Choi] Chpater 6. JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/QFoodCategory.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QTerms.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QMemberAgree.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/generated/umc/spring/domain/mapping/QMemberPrefer.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/MemberRepository/MemberRepository.java
  src/main/java/umc/spring/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/umc/spring/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/umc/spring/repository/MemberRepositoryJPQL.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/MemberService/MemberQueryService.java
  src/main/java/umc/spring/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#18 [Sion] Chapter 6. JPA 활용
  build.gradle
  src/main/generated/umc/study/domain/QFoodCategory.java
  src/main/generated/umc/study/domain/QMember.java
  src/main/generated/umc/study/domain/QMemberAgree.java
  src/main/generated/umc/study/domain/QMemberMission.java
  src/main/generated/umc/study/domain/QMemberPrefer.java
  src/main/generated/umc/study/domain/QMission.java
  src/main/generated/umc/study/domain/QRegion.java
  src/main/generated/umc/study/domain/QReview.java
  src/main/generated/umc/study/domain/QReviewImage.java
  src/main/generated/umc/study/domain/QStore.java
  src/main/generated/umc/study/domain/QTerms.java
  src/main/generated/umc/study/domain/common/QBaseEntity.java
  src/main/java/umc/study/Application.java
  src/main/java/umc/study/config/QueryDSLConfig.java
  src/main/java/umc/study/domain/FoodCategory.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/MemberAgree.java
  src/main/java/umc/study/domain/MemberMission.java
  src/main/java/umc/study/domain/MemberPrefer.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Region.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/ReviewImage.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/domain/Terms.java
  src/main/java/umc/study/domain/common/BaseEntity.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/study/service/StoreService/StoreQueryService.java
  src/main/java/umc/study/service/StoreService/StoreQueryServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Chapter06

#22 [Bibam] Chapter 6. JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/QFoodCategory.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QReviewImage.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QTerms.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QMemberAgree.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/generated/umc/spring/domain/mapping/QMemberPrefer.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#26 [Choi] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/domain/Terms.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#28 [Sion] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/study/apiPayLoad/ApiResponse.java
  src/main/java/umc/study/apiPayLoad/code/BaseCode.java
  src/main/java/umc/study/apiPayLoad/code/BaseErrorCode.java
  src/main/java/umc/study/apiPayLoad/code/ErrorReasonDTO.java
  src/main/java/umc/study/apiPayLoad/code/ReasonDTO.java
  src/main/java/umc/study/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayLoad/code/status/SuccessStatus.java
  src/main/java/umc/study/apiPayLoad/exception/ExceptionAdvice.java
  src/main/java/umc/study/apiPayLoad/exception/GeneralException.java
  src/main/java/umc/study/apiPayLoad/exception/handler/TempHandler.java
  src/main/java/umc/study/converter/TempConverter.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/Region.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/domain/Terms.java
  src/main/java/umc/study/domain/commom/BaseEntity.java
  src/main/java/umc/study/service/TempService/TempCommandQueryImpl.java
  src/main/java/umc/study/service/TempService/TempCommandService.java
  src/main/java/umc/study/service/TempService/TempQueryService.java
  src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/study/web/controller/TempRestController.java
  src/main/java/umc/study/web/dto/TempResponse.java
Labels: ✨ Chapter07

#29 [Maro] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/ApiPayload/ApiResponse.java
  src/main/java/umc/spring/ApiPayload/code/BaseCode.java
  src/main/java/umc/spring/ApiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/ApiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/ApiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/ApiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/ApiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/ApiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/ApiPayload/exception/GeneralException.java
  src/main/java/umc/spring/ApiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#24 [Bibam] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/apiPayoad/ApiResponse.java
  src/main/java/umc/spring/apiPayoad/code/BaseCode.java
  src/main/java/umc/spring/apiPayoad/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayoad/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayoad/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayoad/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayoad/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayoad/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayoad/exception/GeneralException.java
  src/main/java/umc/spring/apiPayoad/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempResponse.java
  src/main/java/umc/spring/web/dto/TempResquest.java
Labels: ✨ Chapter07

#32 [Sion] API & Swagger & Annotation
  build.gradle
  src/main/java/umc/study/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayLoad/exception/handler/FoodCategoryHandler.java
  src/main/java/umc/study/config/SwaggerConfig.java
  src/main/java/umc/study/converter/MemberConverter.java
  src/main/java/umc/study/converter/MemberPreferConverter.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/MemberPrefer.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/repository/FoodCategoryRepository/FoodCategoryRepository.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepository.java
  src/main/java/umc/study/service/MemberService/MemberCommandService.java
  src/main/java/umc/study/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/study/validation/annotation/ExistCategories.java
  src/main/java/umc/study/validation/validator/CategoriesExistValidator.java
  src/main/java/umc/study/web/controller/MemberRestController.java
  src/main/java/umc/study/web/dto/MemberRequestDTO.java
  src/main/java/umc/study/web/dto/MemberResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#39 [ Maro] Chapter 8. API & Swagger & Annotation (Review API)
  src/main/java/umc/spring/ApiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/ApiPayload/exception/handler/MemberHandler.java
  src/main/java/umc/spring/ApiPayload/exception/handler/StoreHandler.java
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/repository/RegionRepository.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/service/RegoinService/RegionRepositoryService.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandService.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistMembers.java
  src/main/java/umc/spring/validation/annotation/ExistRegions.java
  src/main/java/umc/spring/validation/validator/MembersExistValidator.java
  src/main/java/umc/spring/validation/validator/RegionExistValidator.java
  src/main/java/umc/spring/web/controller/ReviewRestController.java
  src/main/java/umc/spring/web/dto/MemberRequestDTO.java
  src/main/java/umc/spring/web/dto/ReviewRequestDTO.java
  src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#48 [Choi] Chapter 8. API & Swagger & Annotation (Review API)
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/handler/MemberHandler.java
  src/main/java/umc/spring/apiPayload/exception/handler/StoreHandler.java
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandService.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistMembers.java
  src/main/java/umc/spring/validation/annotation/ExistStores.java
  src/main/java/umc/spring/validation/validator/MembersExistValidator.java
  src/main/java/umc/spring/validation/validator/StoresExistValidator.java
  src/main/java/umc/spring/web/controller/ReviewRestController.java
  src/main/java/umc/spring/web/dto/ReviewRequestDTO.java
  src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#46 [Sion] API & Swagger & Annotation (ReviewAdd)
  src/main/java/umc/study/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayLoad/exception/handler/MemberHandler.java
  src/main/java/umc/study/apiPayLoad/exception/handler/StoreHandler.java
  src/main/java/umc/study/converter/review/ReviewConverter.java
  src/main/java/umc/study/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/study/service/MemberService/MemberRepositoryService.java
  src/main/java/umc/study/service/MemberService/StoreRepositoryService.java
  src/main/java/umc/study/service/ReviewService/ReviewCommandService.java
  src/main/java/umc/study/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/study/validation/annotation/ExistMembers.java
  src/main/java/umc/study/validation/annotation/ExistStores.java
  src/main/java/umc/study/validation/validator/MemberExistValidator.java
  src/main/java/umc/study/validation/validator/StoreExistValidator.java
  src/main/java/umc/study/web/controller/ReviewRestController.java
  src/main/java/umc/study/web/dto/ReviewRequestDTO.java
  src/main/java/umc/study/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#55 [Bibam] Chapter 8. API & Swagger & Annotation (미션 도전하기)
  src/main/java/umc/spring/apiPayoad/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayoad/exception/handler/MemberHandler.java
  src/main/java/umc/spring/apiPayoad/exception/handler/MissionHandler.java
  src/main/java/umc/spring/converter/MemberMissionConverter.java
  src/main/java/umc/spring/domain/mapping/MemberMission.java
  src/main/java/umc/spring/repository/MemberMissionRepository.java
  src/main/java/umc/spring/repository/MissionRepository.java
  src/main/java/umc/spring/service/MissionService/MemberMissionCommandService.java
  src/main/java/umc/spring/service/MissionService/MemberMissionCommandServiceImpl.java
  src/main/java/umc/spring/validation/annotation/IsChallenging.java
  src/main/java/umc/spring/validation/validator/ChallengingValidator.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/dto/MissionRequestDTO.java
  src/main/java/umc/spring/web/dto/MissionResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#42 [Sion] API & Swagger & Annotation (StoreAdd)
  src/main/java/umc/study/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayLoad/exception/handler/RegionHandler.java
  src/main/java/umc/study/converter/StoreConverter.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/repository/RegionRepository/RegionRepository.java
  src/main/java/umc/study/service/StoreService/RegionRepositoryService.java
  src/main/java/umc/study/service/StoreService/StoreCommandService.java
  src/main/java/umc/study/service/StoreService/StoreCommandServiceImpl.java
  src/main/java/umc/study/validation/annotation/ExistRegions.java
  src/main/java/umc/study/validation/validator/RegionExistValidator.java
  src/main/java/umc/study/web/controller/StoreRestController.java
  src/main/java/umc/study/web/dto/MemberRequestDTO.java
  src/main/java/umc/study/web/dto/store/StoreRequestDTO.java
  src/main/java/umc/study/web/dto/store/StoreResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#49 [Maro] Chapter 8. API & Swagger & Annotation (Mission CHALLENGING API)
  src/main/java/umc/spring/ApiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/ApiPayload/exception/handler/MissionHandler.java
  src/main/java/umc/spring/converter/MissionConverter.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/repository/MemberMissionRepository.java
  src/main/java/umc/spring/repository/MissionRepository.java
  src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/spring/service/MemberService/MemberQueryService.java
  src/main/java/umc/spring/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/umc/spring/service/MissionService/MissionCommandService.java
  src/main/java/umc/spring/service/MissionService/MissionCommandServiceImpl.java
  src/main/java/umc/spring/validation/annotation/AlreadyChallengingMission.java
  src/main/java/umc/spring/validation/validator/MissionsAlreadyChallengingValidator.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/dto/MissionRequestDTO.java
  src/main/java/umc/spring/web/dto/MissionResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#57 [Choi] Chapter 8. API & Swagger & Annotation (StoreAdd API)
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/RegionRepository.java
  src/main/java/umc/spring/repository/StoreRepository.java
  src/main/java/umc/spring/repository/TempStoreRepository/TempStoreRepository.java
  src/main/java/umc/spring/repository/TempStoreRepository/TempStoreRepositoryCustom.java
  src/main/java/umc/spring/repository/TempStoreRepository/TempStoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreCommandService.java
  src/main/java/umc/spring/service/StoreService/StoreCommandServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistRegions.java
  src/main/java/umc/spring/validation/validator/RegionsExistValidator.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/StoreRequestDTO.java
  src/main/java/umc/spring/web/dto/StoreResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#63 [Choi] Chapter 9. API & Paging 실습
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/repository/StoreRepository.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreCommandService.java
  src/main/java/umc/spring/service/StoreService/StoreCommandServiceImpl.java
  src/main/java/umc/spring/validation/validator/StoresExistValidator.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/StoreResponseDTO.java
Labels: ✨ Chapter09

#71 [Sion] Chapter 9. API & Paging (getMyReviews)
  src/main/java/umc/study/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/study/converter/review/ReviewConverter.java
  src/main/java/umc/study/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/study/service/MemberService/MemberReviewQueryService.java
  src/main/java/umc/study/service/MemberService/MemberReviewQueryServiceImpl.java
  src/main/java/umc/study/validation/annotation/CheckPage.java
  src/main/java/umc/study/validation/annotation/ExistMember.java
  src/main/java/umc/study/validation/validator/CheckPageValidator.java
  src/main/java/umc/study/validation/validator/MemberExistValidator.java
  src/main/java/umc/study/web/controller/MemberRestController.java
  src/main/java/umc/study/web/dto/MemberRequestDTO.java
  src/main/java/umc/study/web/dto/ReviewRequestDTO.java
  src/main/java/umc/study/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#75 [Sion] Chapter 9. API & Paging (getChallengingMissions)
  src/main/java/umc/study/converter/MemberMissionConverter.java
  src/main/java/umc/study/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/umc/study/service/MissionService/MyMissionQueryService.java
  src/main/java/umc/study/service/MissionService/MyMissionQueryServiceImpl.java
  src/main/java/umc/study/validation/annotation/ExistMembers.java
  src/main/java/umc/study/web/controller/MemberRestController.java
  src/main/java/umc/study/web/dto/MyMissionResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#65 [Choi] Chapter 9. API & Paging (getMyReviews)
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/service/MemberService/MemberCommandService.java
  src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreCommandServiceImpl.java
  src/main/java/umc/spring/validation/annotation/CheckPage.java
  src/main/java/umc/spring/validation/validator/PageCheckValidator.java
  src/main/java/umc/spring/web/controller/MemberRestController.java
  src/main/java/umc/spring/web/dto/MemberResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#77 [Bibam] Chapter 9. API & Paging (내가 작성한 리뷰 목록 API)
  src/main/java/umc/spring/apiPayoad/code/status/ErrorStatus.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistStore.java
  src/main/java/umc/spring/validation/annotation/IsPositive.java
  src/main/java/umc/spring/validation/validator/PositiveValidator.java
  src/main/java/umc/spring/validation/validator/StoreExistValidator.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/StoreResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#67 [Choi] Chapter 9. API & Paging (getStoreMissions)
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/repository/MissionRepository.java
  src/main/java/umc/spring/service/StoreService/StoreCommandService.java
  src/main/java/umc/spring/service/StoreService/StoreCommandServiceImpl.java
  src/main/java/umc/spring/validation/annotation/CheckPage.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/StoreResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#70 [Choi] Chapter 9. API & Paging (getChallengingMissions)
  src/main/java/umc/spring/converter/MemMissionConverter.java
  src/main/java/umc/spring/repository/MemMissionRepository.java
  src/main/java/umc/spring/service/MemMissionService/MemMissionService.java
  src/main/java/umc/spring/service/MemMissionService/MemMissionServiceImpl.java
  src/main/java/umc/spring/validation/annotation/CheckPage.java
  src/main/java/umc/spring/web/controller/MemMissionRestController.java
  src/main/java/umc/spring/web/dto/MemMissionResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#79 [Bibam] Chapter 9. API & Paging (특정 가게 미션 목록 API)
  src/main/java/umc/spring/apiPayoad/code/status/ErrorStatus.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/repository/MissionRepository.java
  src/main/java/umc/spring/service/StoreMissionService/StoreMissionCommandServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistStore.java
  src/main/java/umc/spring/validation/validator/PositiveValidator.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/StoreResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#81 [Bibam] Chapter 9. API & Paging (진행중인 미션 진행 완료로 바꾸기 API)
  src/main/java/umc/spring/apiPayoad/code/status/ErrorStatus.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/converter/MemberMissionConverter.java
  src/main/java/umc/spring/domain/common/BaseEntity.java
  src/main/java/umc/spring/repository/MemberMissionRepository.java
  src/main/java/umc/spring/service/MissionService/MemberMissionCommandService.java
  src/main/java/umc/spring/service/MissionService/MemberMissionCommandServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistMemberMission.java
  src/main/java/umc/spring/validation/validator/MemberMissionExistValidator.java
  src/main/java/umc/spring/web/controller/MemberRestController.java
  src/main/java/umc/spring/web/dto/MemberResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature
