Repository SSUMC-7th/Spring_Boot_C, pull requests merged in 2024-12, with the labels that each got.

#82 [Maro] Chapter 9. API & Paging - GetMyReviews
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/service/MemberService/MemberCommandService.java
  src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/spring/web/controller/MemberRestController.java
  src/main/java/umc/spring/web/dto/MemberResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#83 [Maro] Chapter 9. API & Paging - GetStoreMissions
  src/main/java/umc/spring/ApiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/converter/MissionConverter.java
  src/main/java/umc/spring/repository/MissionRepository.java
  src/main/java/umc/spring/service/MissionService/MissionCommandService.java
  src/main/java/umc/spring/service/MissionService/MissionCommandServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/dto/MissionResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#84 [Maro] Chapter 9. API & Paging - GetMyChallengingMissions
  src/main/java/umc/spring/converter/MemberMissionConverter.java
  src/main/java/umc/spring/repository/MemberMissionRepository.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionCommandService.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionCommandServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/MemberRestController.java
  src/main/java/umc/spring/web/dto/MemberMissionResponseDTO.java
Labels: ✨ Chapter09, :sparkles: feature

#91 [Bibam] Chapter 10. 로그인 및 회원 가입
  build.gradle
  src/main/java/umc/spring/config/security/CustomOAuth2UserService.java
  src/main/java/umc/spring/config/security/CustomUserDetailService.java
  src/main/java/umc/spring/config/security/SecurityConfig.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/web/controller/MemberViewController.java
  src/main/java/umc/spring/web/dto/MemberRequestDTO.java
  src/main/resources/application.yml
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: ✨ Chapter10, :sparkles: feature

#90 [Choi] Chapter 10. 로그인 및 회원 가입
  build.gradle
  src/main/generated/umc/spring/domain/QMember.java
  src/main/java/umc/spring/config/security/CustomOAuth2UserService.java
  src/main/java/umc/spring/config/security/CustomUserDetailsService.java
  src/main/java/umc/spring/config/security/SecurityConfig.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/enums/Role.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/spring/web/controller/MemberViewController.java
  src/main/java/umc/spring/web/dto/MemberRequestDTO.java
  src/main/resources/application.yml
  src/main/resources/templates/admin.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: ✨ Chapter10

#88 [Sion] Chapter 10. 로그인 및 회원 가입
  build.gradle
  src/main/generated/umc/study/domain/QMember.java
  src/main/java/umc/study/config/security/CustomOAuth2UserService.java
  src/main/java/umc/study/config/security/CustomUserDetailsService.java
  src/main/java/umc/study/config/security/SecurityConfig.java
  src/main/java/umc/study/converter/MemberConverter.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/enums/Role.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepository.java
  src/main/java/umc/study/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/study/web/controller/MemberViewController.java
  src/main/java/umc/study/web/dto/MemberRequestDTO.java
  src/main/resources/application.yml
  src/main/resources/templates/admin.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: ✨ Chapter10

#89 [Maro] Chapter 10. 로그인 및 회원 가입
  build.gradle
  src/main/generated/umc/spring/domain/QMember.java
  src/main/java/umc/spring/config/security/CustomOAuth2UserService.java
  src/main/java/umc/spring/config/security/CustomUserDetailService.java
  src/main/java/umc/spring/config/security/SecurityConfig.java
  src/main/java/umc/spring/converter/MemberConverter.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/enums/Role.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/service/MemberMissionService/MemberMissionCommandServiceImpl.java
  src/main/java/umc/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/spring/web/controller/MemberViewController.java
  src/main/java/umc/spring/web/dto/MemberRequestDTO.java
  src/main/resources/application.yml
  src/main/resources/templates/admin.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: ✨ Chapter10, :sparkles: feature
