Repository SSUMC-7th/Spring_Boot_C, pull requests merged in 2024-10, with the labels that each got.

#2 [Maro] Chapter 3. API URL의 설계 & 프로젝트 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/umc/spring/Application.java
  src/main/resources/application.properties
  src/test/java/umc/spring/ApplicationTests.java
Labels: ✨ Chapter03

#3 [Sion] Chapter 3. API URL의 설계 & 프로젝트 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/umc/spring/Application.java
  src/main/resources/application.properties
  src/test/java/umc/spring/ApplicationTests.java
Labels: ✨ Chapter03

#4 [Choi] Chapter 3. API URL의 설계 & 프로젝트 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/umc/spring/Application.java
  src/main/resources/application.properties
  src/test/java/umc/spring/ApplicationTests.java
Labels: ✨ Chapter03

#5 [Bibam] Chapter 3. API URL의 설계 & 프로젝트 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/umc/spring/Application.java
  src/main/resources/application.properties
  src/test/java/umc/spring/ApplicationTests.java
Labels: ✨ Chapter03

#10 [Choi] Chapter 4. Spring Boot의 코어 개념
  build.gradle
  src/main/resources/application.properties
Labels: ✨ Chapter04

#9 [Sion] Chapter 4. Spring Boot의 코어 개념
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Chapter04

#11 [Bibam] Chapter 4. Spring Boot의 코어 개념
  build.gradle
  src/main/resources/application.yml
Labels: ✨ Chapter04

#15 [Choi] Chapter 5. JPA 기초 및 프로젝트 구조
  build.gradle
  settings.gradle
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/domain/FoodCategory.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/Region.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/domain/Terms.java
  src/main/java/umc/spring/domain/common/BaseEntity.java
  src/main/java/umc/spring/domain/enums/Gender.java
  src/main/java/umc/spring/domain/enums/MemberStatus.java
  src/main/java/umc/spring/domain/enums/MissionStatus.java
  src/main/java/umc/spring/domain/enums/SocialType.java
  src/main/java/umc/spring/domain/mapping/MemberAgree.java
  src/main/java/umc/spring/domain/mapping/MemberMission.java
  src/main/java/umc/spring/domain/mapping/MemberPrefer.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Chapter05

#12 [Sion] Chapter 5. JPA 기초 및 프로젝트 구조
  build.gradle
  src/main/java/umc/study/Application.java
  src/main/java/umc/study/domain/FoodCategory.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/MemberAgree.java
  src/main/java/umc/study/domain/MemberMission.java
  src/main/java/umc/study/domain/MemberPrefer.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Region.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/ReviewImage.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/domain/Terms.java
  src/main/java/umc/study/domain/commom/BaseEntity.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/enums/MemberStatus.java
  src/main/java/umc/study/domain/enums/MissionStatus.java
  src/main/java/umc/study/domain/enums/SocialType.java
  src/main/resources/application.yml
  src/test/java/umc/study/ApplicationTests.java
Labels: ✨ Chapter05
